# Generated by Django 5.0.7 on 2024-09-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddr',
            old_name='address',
            new_name='shipping_address',
        ),
        migrations.RenameField(
            model_name='shippingaddr',
            old_name='City',
            new_name='shipping_city',
        ),
        migrations.RenameField(
            model_name='shippingaddr',
            old_name='Country',
            new_name='shipping_country',
        ),
        migrations.RenameField(
            model_name='shippingaddr',
            old_name='email',
            new_name='shipping_email',
        ),
        migrations.RenameField(
            model_name='shippingaddr',
            old_name='order_date',
            new_name='shipping_order_date',
        ),
        migrations.RenameField(
            model_name='shippingaddr',
            old_name='phone_number',
            new_name='shipping_phone_number',
        ),
        migrations.RenameField(
            model_name='shippingaddr',
            old_name='State',
            new_name='shipping_state',
        ),
    ]
