# Generated by Django 5.0.7 on 2024-09-30 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_delete_orderitem'),
        ('payment', '0002_rename_address_shippingaddr_shipping_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddr',
            name='shipping_order_date',
        ),
        migrations.AlterField(
            model_name='shippingaddr',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_phone_number', models.CharField(max_length=20)),
                ('shipping_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('shipping_address', models.CharField(default='', max_length=500)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=16)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('pirce', models.DecimalField(decimal_places=2, max_digits=16)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.product')),
            ],
        ),
    ]
