# Generated by Django 5.0.7 on 2024-10-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_shippingaddr_shipping_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='order_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_email',
            new_name='order_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_phone_number',
            new_name='order_phone_number',
        ),
        migrations.RenameField(
            model_name='shippingaddr',
            old_name='name',
            new_name='shipping_name',
        ),
        migrations.AddField(
            model_name='order',
            name='order_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
