# Generated by Django 5.0.7 on 2024-10-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_shipping_address_order_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_name',
            field=models.TextField(default='', max_length=100),
        ),
    ]
