# Generated by Django 5.0.7 on 2024-10-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_order_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_address',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
