# Generated by Django 5.0.7 on 2024-10-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_order_order_address_alter_order_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='pirce',
            new_name='price',
        ),
    ]
