# Generated by Django 5.0.7 on 2024-10-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_rename_order_status_order_order_shipped_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_shipped',
            new_name='shipped',
        ),
    ]
