# Generated by Django 6.0.6 on 2026-06-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_orderview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddr',
            options={'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingaddr',
            name='shipping_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='shippingaddr',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddr',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddr',
            name='shipping_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddr',
            name='shipping_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingaddr',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
