# Generated by Django 5.0.7 on 2024-09-02 13:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=350, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('image', models.ImageField(upload_to='uploads/product/')),
                ('size', models.IntegerField(blank=True, default=0, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('category_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(default='', max_length=500)),
                ('quantity', models.IntegerField(default=1)),
                ('phone_number', models.CharField(max_length=20)),
                ('order_date', models.DateField(default=datetime.datetime.today)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('status', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.product')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.user')),
            ],
        ),
    ]
