# Generated by Django 5.0.7 on 2024-09-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_user_user_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
