# Generated by Django 5.0.7 on 2024-09-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_shippingaddr'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transacton_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
