# Generated by Django 5.0.7 on 2024-09-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
