# Generated by Django 5.0.7 on 2024-09-28 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_remove_orderitem_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shippingaddr',
        ),
    ]
