# Generated by Django 5.0.7 on 2024-09-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_delete_shippingaddr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orderitem',
        ),
    ]
