# Generated by Django 5.0.7 on 2024-10-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
