# Generated by Django 5.0.7 on 2025-01-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feauture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
