# Generated by Django 5.0.7 on 2025-01-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0025_product_feauture_alter_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='feauture',
            new_name='feature',
        ),
    ]
