# Generated by Django 5.0.7 on 2025-01-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0026_rename_feauture_product_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
