# Generated by Django 3.2.12 on 2025-02-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0027_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/media/uploads/product/'),
        ),
    ]
