# Generated by Django 6.0.6 on 2026-06-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0030_pushsubscription_delete_emailtemplate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
